version: '3.7'
services:
  db:
    image: 'postgres:latest'
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: redis
    command: redis-server
    volumes:
      - 'redis:/data'
    ports:
      - '6379:6379'
  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq
    links:
      - db
      - redis
    env_file:
      - .env
  rails:
    build: ./
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - .:/docker/app # add our local code to dockerfile
    depends_on:
      - db
      - redis
    env_file:
      - .env

volumes:
  redis:
  postgres: # named volume
