version: '3.7'
services:
  db:
    image: 'postgres:latest'
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: redis
    command: redis-server
    volumes:
      - 'redis:/data'
    ports:
      - '6379:6379'
  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq
    links:
      - db
      - redis
    env_file:
      - .env
  rails:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
      - redis
    env_file:
      - .env
  nginx:
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
    depends_on:
      - rails
    ports:
      - 80:80
    volumes:
     - ./public:/rails/public


volumes:
  redis:
  postgres: # named volume
